### ISSUE TITLE
swap pepsin 1.3 and pepsin > 2 cleavage rules

### ISSUE THREAD

**Issue by jeanmanguy** [sgibb/cleaver#6]
Here, the regex for pepsin 1.3 (`[FLWY]`) is less stringent than the one for pepsin > 2 (`[FL]`)
https://github.com/sgibb/cleaver/blob/c02266a21e422dfe4336cec02a755cc3204ced59/R/rules.R#L60-L63
But in the documentation of [peptidecutter it says that pepsin at pH 1.3 is more specific](https://web.expasy.org/peptide_cutter/peptidecutter_enzymes.html#Peps).

Should the label for these regular expressions be swapped?

**Comment by sgibb** [comment]
You are totally right! Thanks a lot for finding and reporting this problem!
